# Generated by Django 4.1.2 on 2022-10-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('size', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=25)),
                ('image', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
