# Generated by Django 4.1.2 on 2022-11-15 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_product_size_productsize_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
