# Generated by Django 4.1.2 on 2022-11-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_product_size_alter_productsize_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsize',
            old_name='size',
            new_name='product',
        ),
        migrations.AddField(
            model_name='productsize',
            name='name',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
