# Generated by Django 4.1.2 on 2022-10-13 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.1)]),
            preserve_default=False,
        ),
    ]
