# Generated by Django 4.1.2 on 2022-11-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_size_productsize_product_productsize_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('M', 'Men'), ('F', 'Women'), ('C', 'Children')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
