# Generated by Django 4.1.2 on 2022-11-17 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_product_size_delete_productsize_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='label',
        ),
    ]
