# Generated by Django 4.1.2 on 2022-11-28 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['id']},
        ),
    ]
