# Generated by Django 4.1.2 on 2022-11-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='item',
            new_name='product',
        ),
    ]
