# Generated by Django 4.1.2 on 2022-12-10 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_rename_date_created_order_date_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
