# Generated by Django 4.1.2 on 2022-12-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='save_to_profile',
            field=models.BooleanField(default=False),
        ),
    ]
