# Generated by Django 4.1.2 on 2022-12-13 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_shippingaddress_save_to_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='save_to_profile',
        ),
    ]
