# Generated by Django 4.1.2 on 2022-12-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_remove_shippingaddress_save_to_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='state_region',
            field=models.CharField(max_length=100, null=True, verbose_name='State/Region'),
        ),
    ]
