# Generated by Django 4.1.2 on 2022-12-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_shippingaddress_state_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='recipient_first_name',
            field=models.CharField(default=1, max_length=30, verbose_name='First name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='recipient_last_name',
            field=models.CharField(default=1, max_length=30, verbose_name='Last name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='recipient_phone_number',
            field=models.CharField(default=1, max_length=14, verbose_name='Phone number'),
            preserve_default=False,
        ),
    ]
