# Generated by Django 4.1.2 on 2022-10-13 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_alter_firstprojectuser_last_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FirstProjectUser',
            new_name='AppUser',
        ),
    ]
