# Generated by Django 4.1.2 on 2022-12-21 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_newsletter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newsletter',
            new_name='Subscribers',
        ),
    ]
