# Generated by Django 4.1.2 on 2022-12-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_newsletter_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
