# Generated by Django 4.1.2 on 2022-12-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_subscribers_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstprojectuser',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
