# Generated by Django 4.1.2 on 2022-12-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_firstprojectuser_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstprojectuser',
            name='is_seller',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
