# Generated by Django 3.2.17 on 2023-02-12 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_firstprojectuser_is_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstprojectuser',
            name='is_seller',
        ),
    ]
