# Generated by Django 3.2.17 on 2023-02-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_firstprojectuser_is_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstprojectuser',
            name='is_seller',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
