# Generated by Django 3.2.17 on 2023-03-11 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_firstprojectuser_is_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstprojectuser',
            name='is_seller',
        ),
    ]
