# Generated by Django 3.2.17 on 2023-03-22 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_firstprojectuser_is_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstprojectuser',
            options={'verbose_name': 'User'},
        ),
    ]
